### ISSUE TITLE
Publish jscex to NuGet

### ISSUE THREAD

**Issue by iceboundrock** [JeffreyZhao/wind#36]
Why not upload this amazing library to the NuGet gallery? :)

**Comment by JeffreyZhao** [comment]
It looks like NuGet is for .NET components - is that really appropriate to put Jscex in it?

**Comment by mouhong** [comment]
NuGet is not only for .NET components. There're already many javascript components in NuGet. For example, twitter bootstrap, jquery, etc.

**Comment by iceboundrock** [comment]
@mouhong is right, here is the jQuery package page on NuGet: https://nuget.org/packages/jQuery

**Comment by JeffreyZhao** [comment]
@mouhong @iceboundrock Thanks, let me take a look on it.

**Comment by JeffreyZhao** [comment]
close due to duplicated issue: https://github.com/JeffreyZhao/jscex/issues/38
