### ISSUE TITLE
赵兄

### ISSUE THREAD

**Issue by blueken** [JeffreyZhao/wind#4]
偶然发现这个好东东. 下下来试用.

Firefox 和 Chrome都可以正常工作. 但 IE7下不报错也没反应是怎么回事.

**Comment by blueken** [comment]
是IE8

**Comment by JeffreyZhao** [comment]
您可以关注下 modal-dialog.html 这个示例的脚本引用的方式，我正在写这方面的文档。

**Comment by blueken** [comment]
抱歉. 范了低级错误.  只加了alert忘记注释掉console.log了.
