### ISSUE TITLE
求教 has no method 'start' 的错误是啥问题

### ISSUE THREAD

**Issue by chatfeed** [JeffreyZhao/wind#49]
求教哪里出错了

<pre><code>
require('../lib/jscex.mysql').jscexify(db);
var testAsync = eval(Jscex.compile("async",function(){
    sql = 'select * from '+opt.db_name+'.'+tb_name+' limit 10';
    var ret = $await(db.queryAsync(sql));
}))

testAsync.start();
</code></pre>

报错内容如下

<pre><code>

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object function () {
                                                                         var _builder_$0 = Jscex.builders["async"];
                                                                         return _builder_$0.Start(this,
                                                                             _builder_$0.Delay(function () {
/*     sql = "select * from " + opt.db_name + "." + tb_name + " limit 10"; */    sql = "select * from " + opt.db_name + "." + tb_name + " limit 10";
/*     var ret = $await(db.queryAsync(sql)); */                                  return _builder_$0.Bind(db.queryAsync(sql), function (ret) {
                                                                                     return _builder_$0.Normal();
                                                                                 });
                                                                             })
                                                                         );
/* } */                                                              } has no method 'start'
    at Object.<anonymous> (/Users/chatfeed/webroot/SGRPG/ServerCode/server/nodejs/logic/test.js:50:11)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

</code></pre>

**Comment by JeffreyZhao** [comment]
Please send questions to the user group (jscex@googlegroups.com), thanks.
