### ISSUE TITLE
为什么找不到文档了？

### ISSUE THREAD

**Issue by zhangfisher** [JeffreyZhao/wind#75]
在http://windjs.org/cn/里面的文档没有？
只有异步模块里面有一些

**Comment by JeffreyZhao** [comment]
有的，看看是不是被墙了。

**Comment by zhangfisher** [comment]
核心模块（TBD）
编译器模块（TBD）
构造器基础模块（TBD）
异步模块
Promise模块（TBD）

这几个链接，只有异步模块，其他的都显示TBD三个字，啥意思？

**Comment by Noeek** [comment]
To Be Continued 的意思吧，老赵赶紧动起来。
